<?php

declare(strict_types=1);

namespace VediSMM;

use VediSMM\Exception\ConfigurationException;

/** Generated from contract/sdk-operations.json. */
final class OperationCatalog
{
    /** @var array<string, array{method: string, path: string, tag: string, authenticated: bool, scopes: list<string>, request_content_types: list<string>, response_statuses: list<string>, capabilities: list<string>}> */
    private const OPERATIONS = [
        "archiveTrackingLink" => [
            'method' => "post",
            'path' => "/tracking-links/{id}/archive",
            'tag' => "Tracking links",
            'authenticated' => true,
            'scopes' => ["tracking:write"],
            'request_content_types' => [],
            'response_statuses' => ["200","400","401","403","404","409","412","413","415","422","428","500","503"],
            'capabilities' => ["authenticated","etag_response","optimistic_concurrency","service_unavailable"],
        ],
        "cancelAccountConnection" => [
            'method' => "delete",
            'path' => "/connection-sessions/{id}",
            'tag' => "Connections",
            'authenticated' => true,
            'scopes' => ["accounts:write"],
            'request_content_types' => [],
            'response_statuses' => ["204","401","403","404","409","500"],
            'capabilities' => ["authenticated"],
        ],
        "changePassword" => [
            'method' => "put",
            'path' => "/me/password",
            'tag' => "Profile",
            'authenticated' => true,
            'scopes' => ["profile:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["204","400","401","403","413","415","422","500"],
            'capabilities' => ["authenticated"],
        ],
        "checkPostConstraints" => [
            'method' => "post",
            'path' => "/posts/constraints",
            'tag' => "Posts",
            'authenticated' => true,
            'scopes' => ["posts:read"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["200","400","401","403","413","415","422","500"],
            'capabilities' => ["authenticated"],
        ],
        "confirmAccountConnection" => [
            'method' => "post",
            'path' => "/connection-sessions/{id}/confirm",
            'tag' => "Connections",
            'authenticated' => true,
            'scopes' => ["accounts:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["200","400","401","403","404","409","413","415","422","500"],
            'capabilities' => ["authenticated","idempotency_key"],
        ],
        "createContentTemplate" => [
            'method' => "post",
            'path' => "/me/templates",
            'tag' => "Preferences",
            'authenticated' => true,
            'scopes' => ["profile:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["201","400","401","403","409","413","415","422","500"],
            'capabilities' => ["authenticated","etag_response"],
        ],
        "createGroup" => [
            'method' => "post",
            'path' => "/groups",
            'tag' => "Groups",
            'authenticated' => true,
            'scopes' => ["groups:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["201","400","401","403","413","415","422","500"],
            'capabilities' => ["authenticated","etag_response"],
        ],
        "createPersonalToken" => [
            'method' => "post",
            'path' => "/personal-tokens",
            'tag' => "Personal tokens",
            'authenticated' => true,
            'scopes' => ["profile:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["201","400","401","403","409","413","415","422","500"],
            'capabilities' => ["authenticated"],
        ],
        "createPostDraft" => [
            'method' => "post",
            'path' => "/posts",
            'tag' => "Posts",
            'authenticated' => true,
            'scopes' => ["posts:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["201","400","401","403","409","413","415","422","500"],
            'capabilities' => ["authenticated","etag_response","idempotency_key"],
        ],
        "createTrackingLink" => [
            'method' => "post",
            'path' => "/tracking-links",
            'tag' => "Tracking links",
            'authenticated' => true,
            'scopes' => ["tracking:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["201","400","401","403","409","413","415","422","500","503"],
            'capabilities' => ["authenticated","etag_response","idempotency_key","service_unavailable"],
        ],
        "createWebhook" => [
            'method' => "post",
            'path' => "/webhooks",
            'tag' => "Webhooks",
            'authenticated' => true,
            'scopes' => ["webhooks:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["201","400","401","403","409","413","415","422","500"],
            'capabilities' => ["authenticated","etag_response","idempotency_key"],
        ],
        "deleteContentTemplate" => [
            'method' => "delete",
            'path' => "/me/templates/{id}",
            'tag' => "Preferences",
            'authenticated' => true,
            'scopes' => ["profile:write"],
            'request_content_types' => [],
            'response_statuses' => ["204","401","403","404","412","428","500"],
            'capabilities' => ["authenticated","optimistic_concurrency"],
        ],
        "deleteGroup" => [
            'method' => "delete",
            'path' => "/groups/{id}",
            'tag' => "Groups",
            'authenticated' => true,
            'scopes' => ["groups:write"],
            'request_content_types' => [],
            'response_statuses' => ["204","401","403","404","412","428","500"],
            'capabilities' => ["authenticated","optimistic_concurrency"],
        ],
        "deleteMe" => [
            'method' => "delete",
            'path' => "/me",
            'tag' => "Profile",
            'authenticated' => true,
            'scopes' => ["profile:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["202","400","401","403","409","413","415","422","500"],
            'capabilities' => ["async_job","authenticated","idempotency_key"],
        ],
        "deleteMedia" => [
            'method' => "delete",
            'path' => "/media/{id}",
            'tag' => "Media",
            'authenticated' => true,
            'scopes' => ["media:write"],
            'request_content_types' => [],
            'response_statuses' => ["204","401","403","404","409","500"],
            'capabilities' => ["authenticated"],
        ],
        "deletePostDraft" => [
            'method' => "delete",
            'path' => "/posts/{id}",
            'tag' => "Posts",
            'authenticated' => true,
            'scopes' => ["posts:write"],
            'request_content_types' => [],
            'response_statuses' => ["204","401","403","404","409","412","428","500"],
            'capabilities' => ["authenticated","optimistic_concurrency"],
        ],
        "deletePostEverywhere" => [
            'method' => "post",
            'path' => "/posts/{id}/delete-everywhere",
            'tag' => "Publication jobs",
            'authenticated' => true,
            'scopes' => ["posts:publish"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["202","400","401","403","404","409","413","415","422","500"],
            'capabilities' => ["async_job","authenticated","idempotency_key"],
        ],
        "deleteWebhook" => [
            'method' => "delete",
            'path' => "/webhooks/{webhook_id}",
            'tag' => "Webhooks",
            'authenticated' => true,
            'scopes' => ["webhooks:write"],
            'request_content_types' => [],
            'response_statuses' => ["204","401","403","404","412","428","500"],
            'capabilities' => ["authenticated","optimistic_concurrency"],
        ],
        "disableTrackingLink" => [
            'method' => "post",
            'path' => "/tracking-links/{id}/disable",
            'tag' => "Tracking links",
            'authenticated' => true,
            'scopes' => ["tracking:write"],
            'request_content_types' => [],
            'response_statuses' => ["200","400","401","403","404","409","412","413","415","422","428","500","503"],
            'capabilities' => ["authenticated","etag_response","optimistic_concurrency","service_unavailable"],
        ],
        "disconnectAccount" => [
            'method' => "delete",
            'path' => "/accounts/{id}",
            'tag' => "Accounts",
            'authenticated' => true,
            'scopes' => ["accounts:write"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","404","409","500"],
            'capabilities' => ["authenticated"],
        ],
        "forgotPassword" => [
            'method' => "post",
            'path' => "/auth/forgot-password",
            'tag' => "Auth",
            'authenticated' => false,
            'scopes' => [],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["202","400","413","415","422","429","500","503"],
            'capabilities' => ["async_job","service_unavailable"],
        ],
        "getAccount" => [
            'method' => "get",
            'path' => "/accounts/{id}",
            'tag' => "Accounts",
            'authenticated' => true,
            'scopes' => ["accounts:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","404","500"],
            'capabilities' => ["authenticated"],
        ],
        "getAccountConnection" => [
            'method' => "get",
            'path' => "/connection-sessions/{id}",
            'tag' => "Connections",
            'authenticated' => true,
            'scopes' => ["accounts:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","404","500"],
            'capabilities' => ["authenticated"],
        ],
        "getAnalyticsAudience" => [
            'method' => "get",
            'path' => "/analytics/audience",
            'tag' => "Analytics",
            'authenticated' => true,
            'scopes' => ["analytics:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","422","500"],
            'capabilities' => ["authenticated"],
        ],
        "getAnalyticsNetworks" => [
            'method' => "get",
            'path' => "/analytics/networks",
            'tag' => "Analytics",
            'authenticated' => true,
            'scopes' => ["analytics:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","422","500"],
            'capabilities' => ["authenticated"],
        ],
        "getAnalyticsSummary" => [
            'method' => "get",
            'path' => "/analytics/summary",
            'tag' => "Analytics",
            'authenticated' => true,
            'scopes' => ["analytics:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","422","500"],
            'capabilities' => ["authenticated"],
        ],
        "getAnalyticsTimeseries" => [
            'method' => "get",
            'path' => "/analytics/timeseries",
            'tag' => "Analytics",
            'authenticated' => true,
            'scopes' => ["analytics:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","422","500"],
            'capabilities' => ["authenticated"],
        ],
        "getContentTemplate" => [
            'method' => "get",
            'path' => "/me/templates/{id}",
            'tag' => "Preferences",
            'authenticated' => true,
            'scopes' => ["profile:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","404","500"],
            'capabilities' => ["authenticated","etag_response"],
        ],
        "getGroup" => [
            'method' => "get",
            'path' => "/groups/{id}",
            'tag' => "Groups",
            'authenticated' => true,
            'scopes' => ["groups:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","404","500"],
            'capabilities' => ["authenticated","etag_response"],
        ],
        "getMe" => [
            'method' => "get",
            'path' => "/me",
            'tag' => "Profile",
            'authenticated' => true,
            'scopes' => ["profile:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","500"],
            'capabilities' => ["authenticated"],
        ],
        "getMedia" => [
            'method' => "get",
            'path' => "/media/{id}",
            'tag' => "Media",
            'authenticated' => true,
            'scopes' => ["media:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","404","500"],
            'capabilities' => ["authenticated"],
        ],
        "getMediaContent" => [
            'method' => "get",
            'path' => "/media/{id}/content",
            'tag' => "Media",
            'authenticated' => true,
            'scopes' => ["media:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","404","500"],
            'capabilities' => ["authenticated","binary_response"],
        ],
        "getNetwork" => [
            'method' => "get",
            'path' => "/networks/{key}",
            'tag' => "Networks",
            'authenticated' => true,
            'scopes' => ["networks:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","404","422","500"],
            'capabilities' => ["authenticated"],
        ],
        "getOpenApi" => [
            'method' => "get",
            'path' => "/openapi.json",
            'tag' => "System",
            'authenticated' => false,
            'scopes' => [],
            'request_content_types' => [],
            'response_statuses' => ["200","500"],
            'capabilities' => [],
        ],
        "getPersonalToken" => [
            'method' => "get",
            'path' => "/personal-tokens/{id}",
            'tag' => "Personal tokens",
            'authenticated' => true,
            'scopes' => ["profile:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","404","500"],
            'capabilities' => ["authenticated"],
        ],
        "getPost" => [
            'method' => "get",
            'path' => "/posts/{id}",
            'tag' => "Posts",
            'authenticated' => true,
            'scopes' => ["posts:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","404","500"],
            'capabilities' => ["authenticated","etag_response"],
        ],
        "getPublicationJob" => [
            'method' => "get",
            'path' => "/jobs/{job_id}",
            'tag' => "Publication jobs",
            'authenticated' => true,
            'scopes' => ["jobs:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","404","500"],
            'capabilities' => ["authenticated"],
        ],
        "getSession" => [
            'method' => "get",
            'path' => "/sessions/{id}",
            'tag' => "Sessions",
            'authenticated' => true,
            'scopes' => ["profile:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","404","500"],
            'capabilities' => ["authenticated"],
        ],
        "getSignatures" => [
            'method' => "get",
            'path' => "/me/signatures",
            'tag' => "Preferences",
            'authenticated' => true,
            'scopes' => ["profile:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","500"],
            'capabilities' => ["authenticated"],
        ],
        "getSignedMediaContent" => [
            'method' => "get",
            'path' => "/media-content",
            'tag' => "Media",
            'authenticated' => false,
            'scopes' => [],
            'request_content_types' => [],
            'response_statuses' => ["200","404","422","500"],
            'capabilities' => ["binary_response"],
        ],
        "getTrackingAnalyticsGeo" => [
            'method' => "get",
            'path' => "/tracking-analytics/geo",
            'tag' => "Tracking analytics",
            'authenticated' => true,
            'scopes' => ["tracking:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","422","500","503"],
            'capabilities' => ["authenticated","service_unavailable"],
        ],
        "getTrackingAnalyticsSummary" => [
            'method' => "get",
            'path' => "/tracking-analytics/summary",
            'tag' => "Tracking analytics",
            'authenticated' => true,
            'scopes' => ["tracking:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","422","500","503"],
            'capabilities' => ["authenticated","service_unavailable"],
        ],
        "getTrackingAnalyticsTimeseries" => [
            'method' => "get",
            'path' => "/tracking-analytics/timeseries",
            'tag' => "Tracking analytics",
            'authenticated' => true,
            'scopes' => ["tracking:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","422","500","503"],
            'capabilities' => ["authenticated","service_unavailable"],
        ],
        "getTrackingLink" => [
            'method' => "get",
            'path' => "/tracking-links/{id}",
            'tag' => "Tracking links",
            'authenticated' => true,
            'scopes' => ["tracking:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","404","500","503"],
            'capabilities' => ["authenticated","etag_response","service_unavailable"],
        ],
        "getWebhook" => [
            'method' => "get",
            'path' => "/webhooks/{webhook_id}",
            'tag' => "Webhooks",
            'authenticated' => true,
            'scopes' => ["webhooks:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","404","500"],
            'capabilities' => ["authenticated","etag_response"],
        ],
        "getWebhookDelivery" => [
            'method' => "get",
            'path' => "/webhooks/{webhook_id}/deliveries/{delivery_id}",
            'tag' => "Webhooks",
            'authenticated' => true,
            'scopes' => ["webhooks:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","404","500"],
            'capabilities' => ["authenticated"],
        ],
        "listAccounts" => [
            'method' => "get",
            'path' => "/accounts",
            'tag' => "Accounts",
            'authenticated' => true,
            'scopes' => ["accounts:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","400","401","403","422","500"],
            'capabilities' => ["authenticated","cursor_pagination"],
        ],
        "listAnalyticsPosts" => [
            'method' => "get",
            'path' => "/analytics/posts",
            'tag' => "Analytics",
            'authenticated' => true,
            'scopes' => ["analytics:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","400","401","403","422","500"],
            'capabilities' => ["authenticated","cursor_pagination"],
        ],
        "listAuditEvents" => [
            'method' => "get",
            'path' => "/audit-events",
            'tag' => "Audit",
            'authenticated' => true,
            'scopes' => ["profile:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","400","401","403","422","500"],
            'capabilities' => ["authenticated","cursor_pagination"],
        ],
        "listCalendarEvents" => [
            'method' => "get",
            'path' => "/calendar",
            'tag' => "Calendar",
            'authenticated' => true,
            'scopes' => ["calendar:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","400","401","403","422","500"],
            'capabilities' => ["authenticated","cursor_pagination"],
        ],
        "listContentTemplates" => [
            'method' => "get",
            'path' => "/me/templates",
            'tag' => "Preferences",
            'authenticated' => true,
            'scopes' => ["profile:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","400","401","403","422","500"],
            'capabilities' => ["authenticated","cursor_pagination"],
        ],
        "listGroups" => [
            'method' => "get",
            'path' => "/groups",
            'tag' => "Groups",
            'authenticated' => true,
            'scopes' => ["groups:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","400","401","403","422","500"],
            'capabilities' => ["authenticated","cursor_pagination"],
        ],
        "listMedia" => [
            'method' => "get",
            'path' => "/media",
            'tag' => "Media",
            'authenticated' => true,
            'scopes' => ["media:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","400","401","403","422","500"],
            'capabilities' => ["authenticated","cursor_pagination"],
        ],
        "listNetworks" => [
            'method' => "get",
            'path' => "/networks",
            'tag' => "Networks",
            'authenticated' => true,
            'scopes' => ["networks:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","422","500"],
            'capabilities' => ["authenticated"],
        ],
        "listPersonalTokens" => [
            'method' => "get",
            'path' => "/personal-tokens",
            'tag' => "Personal tokens",
            'authenticated' => true,
            'scopes' => ["profile:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","500"],
            'capabilities' => ["authenticated"],
        ],
        "listPosts" => [
            'method' => "get",
            'path' => "/posts",
            'tag' => "Posts",
            'authenticated' => true,
            'scopes' => ["posts:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","400","401","403","422","500"],
            'capabilities' => ["authenticated","cursor_pagination"],
        ],
        "listPublicationJobs" => [
            'method' => "get",
            'path' => "/jobs",
            'tag' => "Publication jobs",
            'authenticated' => true,
            'scopes' => ["jobs:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","400","401","403","422","500"],
            'capabilities' => ["authenticated","cursor_pagination"],
        ],
        "listSessions" => [
            'method' => "get",
            'path' => "/sessions",
            'tag' => "Sessions",
            'authenticated' => true,
            'scopes' => ["profile:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","500"],
            'capabilities' => ["authenticated"],
        ],
        "listTrackingAnalyticsLinks" => [
            'method' => "get",
            'path' => "/tracking-analytics/links",
            'tag' => "Tracking analytics",
            'authenticated' => true,
            'scopes' => ["tracking:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","400","401","403","422","500","503"],
            'capabilities' => ["authenticated","cursor_pagination","service_unavailable"],
        ],
        "listTrackingAnalyticsPosts" => [
            'method' => "get",
            'path' => "/tracking-analytics/posts",
            'tag' => "Tracking analytics",
            'authenticated' => true,
            'scopes' => ["tracking:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","400","401","403","422","500","503"],
            'capabilities' => ["authenticated","cursor_pagination","service_unavailable"],
        ],
        "listTrackingAnalyticsSources" => [
            'method' => "get",
            'path' => "/tracking-analytics/sources",
            'tag' => "Tracking analytics",
            'authenticated' => true,
            'scopes' => ["tracking:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","400","401","403","422","500","503"],
            'capabilities' => ["authenticated","cursor_pagination","service_unavailable"],
        ],
        "listTrackingLinks" => [
            'method' => "get",
            'path' => "/tracking-links",
            'tag' => "Tracking links",
            'authenticated' => true,
            'scopes' => ["tracking:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","400","401","403","422","500","503"],
            'capabilities' => ["authenticated","cursor_pagination","service_unavailable"],
        ],
        "listWebhookDeliveries" => [
            'method' => "get",
            'path' => "/webhooks/{webhook_id}/deliveries",
            'tag' => "Webhooks",
            'authenticated' => true,
            'scopes' => ["webhooks:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","400","401","403","404","422","500"],
            'capabilities' => ["authenticated","cursor_pagination"],
        ],
        "listWebhooks" => [
            'method' => "get",
            'path' => "/webhooks",
            'tag' => "Webhooks",
            'authenticated' => true,
            'scopes' => ["webhooks:read"],
            'request_content_types' => [],
            'response_statuses' => ["200","400","401","403","422","500"],
            'capabilities' => ["authenticated","cursor_pagination"],
        ],
        "login" => [
            'method' => "post",
            'path' => "/auth/login",
            'tag' => "Auth",
            'authenticated' => false,
            'scopes' => [],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["200","400","401","413","415","422","429","500","503"],
            'capabilities' => ["service_unavailable"],
        ],
        "logout" => [
            'method' => "post",
            'path' => "/auth/logout",
            'tag' => "Auth",
            'authenticated' => true,
            'scopes' => ["profile:read"],
            'request_content_types' => [],
            'response_statuses' => ["204","401","403","500"],
            'capabilities' => ["authenticated"],
        ],
        "logoutAll" => [
            'method' => "post",
            'path' => "/auth/logout-all",
            'tag' => "Auth",
            'authenticated' => true,
            'scopes' => ["profile:read"],
            'request_content_types' => [],
            'response_statuses' => ["204","401","403","500"],
            'capabilities' => ["authenticated"],
        ],
        "ping" => [
            'method' => "get",
            'path' => "/ping",
            'tag' => "System",
            'authenticated' => false,
            'scopes' => [],
            'request_content_types' => [],
            'response_statuses' => ["200","500"],
            'capabilities' => [],
        ],
        "publishPost" => [
            'method' => "post",
            'path' => "/posts/{id}/publish",
            'tag' => "Publication jobs",
            'authenticated' => true,
            'scopes' => ["posts:publish"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["202","400","401","403","404","409","412","413","415","422","500"],
            'capabilities' => ["async_job","authenticated","idempotency_key"],
        ],
        "refresh" => [
            'method' => "post",
            'path' => "/auth/refresh",
            'tag' => "Auth",
            'authenticated' => false,
            'scopes' => [],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["200","400","401","413","415","422","429","500","503"],
            'capabilities' => ["service_unavailable"],
        ],
        "register" => [
            'method' => "post",
            'path' => "/auth/register",
            'tag' => "Auth",
            'authenticated' => false,
            'scopes' => [],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["202","400","413","415","422","429","500","503"],
            'capabilities' => ["async_job","service_unavailable"],
        ],
        "replaceGroupAccounts" => [
            'method' => "put",
            'path' => "/groups/{id}/accounts",
            'tag' => "Groups",
            'authenticated' => true,
            'scopes' => ["groups:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["200","400","401","403","404","412","413","415","422","428","500"],
            'capabilities' => ["authenticated","etag_response","optimistic_concurrency"],
        ],
        "replaceSignatures" => [
            'method' => "put",
            'path' => "/me/signatures",
            'tag' => "Preferences",
            'authenticated' => true,
            'scopes' => ["profile:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["200","400","401","403","413","415","422","500"],
            'capabilities' => ["authenticated"],
        ],
        "resendVerification" => [
            'method' => "post",
            'path' => "/auth/email/resend",
            'tag' => "Auth",
            'authenticated' => false,
            'scopes' => [],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["202","400","413","415","422","429","500","503"],
            'capabilities' => ["async_job","service_unavailable"],
        ],
        "resetPassword" => [
            'method' => "post",
            'path' => "/auth/reset-password",
            'tag' => "Auth",
            'authenticated' => false,
            'scopes' => [],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["204","400","413","415","422","429","500","503"],
            'capabilities' => ["service_unavailable"],
        ],
        "retryPostTargets" => [
            'method' => "post",
            'path' => "/posts/{id}/retry",
            'tag' => "Publication jobs",
            'authenticated' => true,
            'scopes' => ["posts:publish"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["202","400","401","403","404","409","413","415","422","500"],
            'capabilities' => ["async_job","authenticated","idempotency_key"],
        ],
        "retryWebhookDelivery" => [
            'method' => "post",
            'path' => "/webhooks/{webhook_id}/deliveries/{delivery_id}/retry",
            'tag' => "Webhooks",
            'authenticated' => true,
            'scopes' => ["webhooks:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["202","400","401","403","404","409","413","415","422","500"],
            'capabilities' => ["async_job","authenticated","idempotency_key"],
        ],
        "revokePersonalToken" => [
            'method' => "delete",
            'path' => "/personal-tokens/{id}",
            'tag' => "Personal tokens",
            'authenticated' => true,
            'scopes' => ["profile:write"],
            'request_content_types' => [],
            'response_statuses' => ["204","401","403","404","500"],
            'capabilities' => ["authenticated"],
        ],
        "revokeSession" => [
            'method' => "delete",
            'path' => "/sessions/{id}",
            'tag' => "Sessions",
            'authenticated' => true,
            'scopes' => ["profile:write"],
            'request_content_types' => [],
            'response_statuses' => ["204","401","403","404","500"],
            'capabilities' => ["authenticated"],
        ],
        "rotatePersonalToken" => [
            'method' => "post",
            'path' => "/personal-tokens/{id}/rotate",
            'tag' => "Personal tokens",
            'authenticated' => true,
            'scopes' => ["profile:write"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","404","409","500"],
            'capabilities' => ["authenticated"],
        ],
        "rotateWebhookSecret" => [
            'method' => "post",
            'path' => "/webhooks/{webhook_id}/rotate-secret",
            'tag' => "Webhooks",
            'authenticated' => true,
            'scopes' => ["webhooks:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["200","400","401","403","404","409","413","415","422","500"],
            'capabilities' => ["authenticated","etag_response","idempotency_key"],
        ],
        "schedulePost" => [
            'method' => "post",
            'path' => "/posts/{id}/schedule",
            'tag' => "Posts",
            'authenticated' => true,
            'scopes' => ["posts:publish"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["200","400","401","403","404","409","412","413","415","422","428","500"],
            'capabilities' => ["authenticated","etag_response","optimistic_concurrency"],
        ],
        "startAccountConnection" => [
            'method' => "post",
            'path' => "/connection-sessions",
            'tag' => "Connections",
            'authenticated' => true,
            'scopes' => ["accounts:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["200","201","400","401","403","409","413","415","422","500","502"],
            'capabilities' => ["authenticated","idempotency_key"],
        ],
        "testWebhook" => [
            'method' => "post",
            'path' => "/webhooks/{webhook_id}/test",
            'tag' => "Webhooks",
            'authenticated' => true,
            'scopes' => ["webhooks:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["202","400","401","403","404","409","413","415","422","500"],
            'capabilities' => ["async_job","authenticated","idempotency_key"],
        ],
        "unschedulePost" => [
            'method' => "post",
            'path' => "/posts/{id}/unschedule",
            'tag' => "Posts",
            'authenticated' => true,
            'scopes' => ["posts:publish"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","404","409","412","428","500"],
            'capabilities' => ["authenticated","etag_response","optimistic_concurrency"],
        ],
        "updateContentTemplate" => [
            'method' => "patch",
            'path' => "/me/templates/{id}",
            'tag' => "Preferences",
            'authenticated' => true,
            'scopes' => ["profile:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["200","400","401","403","404","412","413","415","422","428","500"],
            'capabilities' => ["authenticated","etag_response","optimistic_concurrency"],
        ],
        "updateGroup" => [
            'method' => "patch",
            'path' => "/groups/{id}",
            'tag' => "Groups",
            'authenticated' => true,
            'scopes' => ["groups:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["200","400","401","403","404","412","413","415","422","428","500"],
            'capabilities' => ["authenticated","etag_response","optimistic_concurrency"],
        ],
        "updateMe" => [
            'method' => "patch",
            'path' => "/me",
            'tag' => "Profile",
            'authenticated' => true,
            'scopes' => ["profile:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["200","400","401","403","413","415","422","500"],
            'capabilities' => ["authenticated"],
        ],
        "updatePersonalToken" => [
            'method' => "patch",
            'path' => "/personal-tokens/{id}",
            'tag' => "Personal tokens",
            'authenticated' => true,
            'scopes' => ["profile:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["200","400","401","403","404","409","413","415","422","500"],
            'capabilities' => ["authenticated"],
        ],
        "updatePostDraft" => [
            'method' => "patch",
            'path' => "/posts/{id}",
            'tag' => "Posts",
            'authenticated' => true,
            'scopes' => ["posts:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["200","400","401","403","404","409","412","413","415","422","428","500"],
            'capabilities' => ["authenticated","etag_response","optimistic_concurrency"],
        ],
        "updateWebhook" => [
            'method' => "patch",
            'path' => "/webhooks/{webhook_id}",
            'tag' => "Webhooks",
            'authenticated' => true,
            'scopes' => ["webhooks:write"],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["200","400","401","403","404","409","412","413","415","422","428","500"],
            'capabilities' => ["authenticated","etag_response","optimistic_concurrency"],
        ],
        "uploadMedia" => [
            'method' => "post",
            'path' => "/media",
            'tag' => "Media",
            'authenticated' => true,
            'scopes' => ["media:write"],
            'request_content_types' => ["multipart/form-data"],
            'response_statuses' => ["201","401","403","409","413","415","422","429","500","503"],
            'capabilities' => ["authenticated","multipart_upload","service_unavailable"],
        ],
        "verifyAccount" => [
            'method' => "post",
            'path' => "/accounts/{id}/verify",
            'tag' => "Accounts",
            'authenticated' => true,
            'scopes' => ["accounts:write"],
            'request_content_types' => [],
            'response_statuses' => ["200","401","403","404","422","500","502"],
            'capabilities' => ["authenticated"],
        ],
        "verifyEmail" => [
            'method' => "post",
            'path' => "/auth/email/verify",
            'tag' => "Auth",
            'authenticated' => false,
            'scopes' => [],
            'request_content_types' => ["application/json"],
            'response_statuses' => ["204","400","413","415","422","429","500","503"],
            'capabilities' => ["service_unavailable"],
        ],
    ];

    /** @return array<string, array{method: string, path: string, tag: string, authenticated: bool, scopes: list<string>, request_content_types: list<string>, response_statuses: list<string>, capabilities: list<string>}> */
    public static function all(): array
    {
        return self::OPERATIONS;
    }

    public static function get(string $operationId): Operation
    {
        $definition = self::OPERATIONS[$operationId] ?? null;
        if ($definition === null) {
            throw new ConfigurationException('Unknown VediSMM operation: ' . $operationId);
        }

        return Operation::fromArray($operationId, $definition);
    }
}
